preference:
  dim: 5
  Member:
    distribution:
      type: Guassion
      sigma: 1
      mu: 0
      low: None
      high: None
  Work:
    distribution:
      type: Gaussion
      sigma: 1
      mu: 0
      low: None
      high: None
  Logic:
    const:
      a: 1.0
      b: 1.0
      c: 1.0
      quad_token_const: 1.0
